# Generated by Django 3.2.3 on 2021-05-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210531_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_links',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='user_links',
            name='title',
        ),
        migrations.AddField(
            model_name='user_links',
            name='full_link',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_links',
            name='short_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
