# Generated by Django 3.2.3 on 2021-05-31 18:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20210531_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_links',
            new_name='Userlinks',
        ),
    ]
