# Generated by Django 3.2.3 on 2021-05-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_links_userlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('short_link', models.CharField(max_length=100)),
                ('full_link', models.CharField(max_length=250)),
            ],
        ),
    ]
